services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: household-task-manager-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: always