services:
  db:
    image: postgres:16
    container_name: household-task-manager-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["/app/entrypoint.sh"]
    container_name: household-task-manager-backend
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: household-task-manager-frontend
    ports:
      - "3000:4173"
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    command: ["yarn", "preview", "--host"]

volumes:
  postgres_data:
    driver: local