"""Add refresh_token model

Revision ID: 0bcb13197448
Revises: aaafbf42ef8f
Create Date: 2024-10-21 13:57:52.998597

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0bcb13197448"
down_revision: Union[str, None] = "aaafbf42ef8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
