"""Add cascade delete to tasks and project members

Revision ID: 48f7545bac46
Revises: bce682963ea2
Create Date: 2024-10-13 17:37:27.486711

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "48f7545bac46"
down_revision: Union[str, None] = "bce682963ea2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
