"""Change Task Execution Model

Revision ID: 51fc0a40ff2c
Revises: 48f7545bac46
Create Date: 2024-10-13 22:55:47.200251

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "51fc0a40ff2c"
down_revision: Union[str, None] = "48f7545bac46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
