"""Remove project_id from TaskExecution and update relationships

Revision ID: aea86086d0d9
Revises: c8bb7708cfe3
Create Date: 2024-10-13 12:04:15.983000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aea86086d0d9"
down_revision: Union[str, None] = "c8bb7708cfe3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "task_executions_project_id_fkey", "task_executions", type_="foreignkey"
    )
    op.drop_column("task_executions", "project_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_executions",
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "task_executions_project_id_fkey",
        "task_executions",
        "projects",
        ["project_id"],
        ["id"],
    )
    # ### end Alembic commands ###
