"""Add cascade delete to task_executions

Revision ID: bce682963ea2
Revises: aea86086d0d9
Create Date: 2024-10-13 17:07:34.178073

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bce682963ea2"
down_revision: Union[str, None] = "aea86086d0d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
