"""Add description column to Project model

Revision ID: c8bb7708cfe3
Revises:
Create Date: 2024-10-12 23:51:16.426767

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8bb7708cfe3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("description", sa.String(), nullable=True))
    op.add_column(
        "task_executions", sa.Column("project_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "task_executions", "projects", ["project_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task_executions", type_="foreignkey")  # type: ignore
    op.drop_column("task_executions", "project_id")
    op.drop_column("projects", "description")
    # ### end Alembic commands ###
